global:
  scrape_interval: 3s
  scrape_timeout: 3s
  evaluation_interval: 5s
scrape_configs:
- job_name: Application
  static_configs:
  - targets:
    - application:3000
- job_name: Prometheus
  static_configs:
  - targets:
    - metrics:9090
- job_name: Grafana
  static_configs:
  - targets:
    - grafana:3000
- job_name: Zipkin
  metrics_path: /prometheus
  static_configs:
  - targets:
    - zipkin:9411
- job_name: FluentD
  static_configs:
  - targets:
    - fluentd:24231
- job_name: ElasticSearch
  static_configs:
  - targets:
    - elasticsearch_exporter:9108